### ISSUE TITLE
Topics of Feb. 2021

### ISSUE THREAD

**Issue by Liam8** [Liam8/bigdata-knowledge#1]
Hi all,
We can propose new topics of Feb. 2021 now.
Welcome to give your ideas below.

**Comment by HustonPeng** [comment]
I want to introduce the DataStream API's usage and design thought.

**Comment by XavieLee** [comment]
Reading data from Kafka and sink to HDFS according to the partition key is a very general pipeline. Although it is not difficult, it is very practical. This is my suggestion.

**Comment by Timzhouyes** [comment]
Flink slot.

**Comment by ChenLinL** [comment]
I suggest we could start from the bottom the information about how the data be stored and transferred in spark and flink.
